version: '3'
services:
  redis:
    image: redis:latest
    restart: "always"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./conf/redis.conf:/etc/redis/redis.conf
      - ./data/redis:/data
    command: redis-server /etc/redis/redis.conf
    privileged: true
    networks:
      - dreamcity-net

  docker-etcd:
    hostname: etcd
    image: bitnami/etcd:latest
    container_name: etcd
    volumes:
      - ./data/etcd:/bitnami/etcd/data
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
    ports:
      - "2379:2379"
    networks:
      - dreamcity-net

networks:
  dreamcity-net:
    driver: bridge
